<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Jellyfin.Plugin.FanKarrSearch</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.FanKarrSearch</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AssemblyVersion>1.0.6.11</AssemblyVersion>
    <FileVersion>1.0.6.11</FileVersion>
    <Version>1.0.6.11</Version>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="10.11.3">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="10.11.3">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Embed the JS file as a resource so it's packaged in the DLL -->
  <ItemGroup>
    <EmbeddedResource Include="Web\fankarr.js" />
    <EmbeddedResource Include="Web\config.html" />
  </ItemGroup>


</Project>
